#一种数据序列化格式，以数据为核心，重数据轻格式
#规则：
#- 大小写敏感
#- 属性层级关系使用多行描述，每行结尾使用冒号结束
#- 使用缩进表示层级关系，同层级左侧对齐，只允许使用空格（不允许使用Tab键）
#- 属性值前面添加空格（属性名与属性值之间使用冒号+空格作为分隔）
#- #表示注释
#- 核心规则：数据前面要加空格与冒号隔开
server:
  port: 81
  servlet:
    context-path: / #虚拟路径


user:
  name: 张三
  age: 18

enterprise:
  name: ${user.name}
  age: 16
  subject:
    - java
    - 前端
