#设置启用环境
spring:
  profiles:
    active: dev

---
#生产环境
server:
  port: 90
spring:
  profiles: pro
---
#开发环境
server:
  port: 91
spring:
  profiles: dev
---
#  测试环境
server:
  port: 92
spring:
  profiles: test




